function networkClaussenShadowFadingMap = LTE_init_generate_claussen_shadow_fading_map(eNodeBs)
% Generates a shadow fading map based on Claussen's paper "Efficient
% modeling of channel maps with correlated shadow fading in mobile
% radio systems". Extended to correlate the shadow fading maps from
% each of the eNodeBs. 1 map per eNodeB is generated, NOT 1 map per
% sector.
% (c) Josep Colom Ikuno, INTHFT, 2008

global LTE_config;

%% Generate the shadow fading map
print_log(1,'Generating Claussen space-correlated shadow fading map\n');
networkClaussenShadowFadingMap = channel_gain_wrappers.shadowFadingMapClaussen(...
    LTE_config.shadow_fading_map_resolution,...
    LTE_config.roi_x,...
    LTE_config.roi_y,...
    LTE_config.shadow_fading_n_neighbors,...
    eNodeBs,...
    LTE_config.shadow_fading_mean,...
    LTE_config.shadow_fading_sd,...
    LTE_config.r_eNodeBs);

